print("welcome to bill calculator")
currency = input("whats your country's currency called?\n")
bill1 = int(input("how much was the total bill? In integer or decimal\n"))
tip = (int(input("how much tip would you like to give? In percentage\n")))
tip = (tip / 100)
tip = (tip * bill1)
bill1 = (tip + bill1)
split = int(input("how many people to split up the bill with?\n"))
print (f"your bill after adding tip will be {bill1} {currency}. ")
bill1 = (bill1 / split )
bill1 = round(bill1 , 2 )
print (f"each person will have to pay {bill1} {currency}.")
